-- Fill in proper HTML for the 3 templates inserted with placeholder content

UPDATE email_templates SET
  subject  = 'Offer Update - {{offer_name}}',
  body_html = '<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:32px 16px;background:#f8fafc"><div style="background:#ffffff;border-radius:12px;padding:32px;border:1px solid #e2e8f0"><p style="color:#0891b2;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:2px;margin:0 0 8px">{{network_name}}</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:0 0 24px"><h2 style="color:#0f172a;font-size:20px;margin:0 0 16px">Offer Update Notice</h2><p style="color:#334155;line-height:1.7;margin:0 0 12px">Hi {{first_name}},</p><p style="color:#334155;line-height:1.7;margin:0 0 16px">We are writing to let you know that the offer <strong>{{offer_name}}</strong> on <strong>{{network_name}}</strong> has been updated. Please log in to review the latest offer terms and payout details before continuing to promote this offer.</p><a href="{{login_url}}" style="display:inline-block;background:#0891b2;color:#ffffff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px">Review Offer</a><p style="color:#94a3b8;font-size:12px;margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0">This email was sent by {{network_name}}.</p></div></div>'
WHERE slug = 'offer_changed';

UPDATE email_templates SET
  subject  = 'Invoice #{{invoice_number}} - {{amount}}',
  body_html = '<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:32px 16px;background:#f8fafc"><div style="background:#ffffff;border-radius:12px;padding:32px;border:1px solid #e2e8f0"><p style="color:#0891b2;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:2px;margin:0 0 8px">{{network_name}}</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:0 0 24px"><h2 style="color:#0f172a;font-size:20px;margin:0 0 16px">Affiliate Invoice</h2><p style="color:#334155;line-height:1.7;margin:0 0 12px">Hi {{first_name}},</p><p style="color:#334155;line-height:1.7;margin:0 0 16px">Your affiliate invoice <strong>#{{invoice_number}}</strong> for <strong>{{amount}}</strong> has been generated on <strong>{{network_name}}</strong>. You can view and download your invoice from the billing section of your dashboard.</p><a href="{{login_url}}" style="display:inline-block;background:#10b981;color:#ffffff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px">View Invoice</a><p style="color:#94a3b8;font-size:12px;margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0">This email was sent by {{network_name}}.</p></div></div>'
WHERE slug = 'affiliate_invoice';

UPDATE email_templates SET
  subject  = 'Invoice #{{invoice_number}} - {{amount}}',
  body_html = '<div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:32px 16px;background:#f8fafc"><div style="background:#ffffff;border-radius:12px;padding:32px;border:1px solid #e2e8f0"><p style="color:#0891b2;font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:2px;margin:0 0 8px">{{network_name}}</p><hr style="border:none;border-top:1px solid #e2e8f0;margin:0 0 24px"><h2 style="color:#0f172a;font-size:20px;margin:0 0 16px">Advertiser Invoice</h2><p style="color:#334155;line-height:1.7;margin:0 0 12px">Hi {{first_name}},</p><p style="color:#334155;line-height:1.7;margin:0 0 16px">Your advertiser invoice <strong>#{{invoice_number}}</strong> for <strong>{{amount}}</strong> has been generated on <strong>{{network_name}}</strong>. Please log in to your dashboard to review, download, or pay this invoice.</p><a href="{{login_url}}" style="display:inline-block;background:#0891b2;color:#ffffff;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px">View Invoice</a><p style="color:#94a3b8;font-size:12px;margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0">This email was sent by {{network_name}}.</p></div></div>'
WHERE slug = 'advertiser_invoice';
