import { Router } from 'express';
import authRouter from "./auth.route.js";
import clickRouter from "./click.route.js";
import postbackRouter from "./postback.route.js";
import offerRouter from "./offer.route.js";
import applicationRouter from "./application.route.js";
import trackingRouter from "./tracking.route.js";
import publisherPostbackRouter from "./publisher-postback.route.js";
import publisherRouter from "./publisher.route.js";
import analyticsRouter from "./analytics.route.js";
import advertiserRouter from "./advertiser.route.js";
import networkSettingsRouter from "./network-settings.route.js";
import uploadRouter from "./upload.route.js";
import conversionReviewRouter from "./conversion-review.route.js";
import publisherAnalyticsRouter from "./publisher-analytics.route.js";
import adminPostbackRouter from "./admin-postback.route.js";
import notificationsRouter from "./notifications.route.js";
import announcementsRouter from "./announcements.route.js";
import adminAnnouncementsRouter from "./admin-announcements.route.js";
import offerEventsRouter from "./offer-events.route.js";
import offerLandingPagesRouter from "./offer-landing-pages.route.js";
import offerCreativesRouter from "./offer-creatives.route.js";
import offerAssignmentsRouter from "./offer-assignments.route.js";
import offerTargetingRouter from "./targeting.route.js";
import offerCapsRouter from "./caps.route.js";
import offerPublisherDetailRouter from "./offer-publisher-detail.route.js";
import offerCategoriesRouter from "./offer-categories.route.js";
import managersRouter from "./managers.route.js";
import publisherSelfRouter from "./publisher_self.route.js";
import signupQuestionsRouter from "./signup-questions.route.js";
import mailerRouter from "./mailer.route.js";
import verificationRouter from "./verification.route.js";
import publisherApiV1Router from "./publisher-api.route.js";

const router = Router();

router.use('/auth', authRouter);
router.use('/click', clickRouter);
router.use('/postback', postbackRouter);
router.use('/offers', offerRouter);
router.use('/applications', applicationRouter);
router.use('/tracking', trackingRouter);
router.use('/publisher-postbacks', publisherPostbackRouter);
router.use('/publishers', publisherRouter);
router.use('/analytics', analyticsRouter);
router.use('/publisher-stats', publisherAnalyticsRouter);
router.use('/advertisers', advertiserRouter);
router.use('/network-settings', networkSettingsRouter);
router.use('/upload', uploadRouter);
router.use('/conversions/review', conversionReviewRouter);
router.use('/admin/postbacks', adminPostbackRouter);
router.use('/notifications', notificationsRouter);
router.use('/announcements', announcementsRouter);
router.use('/admin/announcements', adminAnnouncementsRouter);
router.use('/offers/:offerId/events', offerEventsRouter);
router.use('/offers/:offerId/landing-pages', offerLandingPagesRouter);
router.use('/offers/:offerId/creatives', offerCreativesRouter);
router.use('/offers/:offerId/assignments', offerAssignmentsRouter);
router.use('/offers/:offerId/targeting', offerTargetingRouter);
router.use('/offers/:offerId/caps', offerCapsRouter);
router.use('/offers/:offerId/publisher-detail', offerPublisherDetailRouter);
router.use('/offer-categories', offerCategoriesRouter);
router.use('/managers', managersRouter);
router.use('/publisher/me', publisherSelfRouter);
router.use('/signup-questions', signupQuestionsRouter);
router.use('/mailer', mailerRouter);
router.use('/verify-email', verificationRouter);
router.use('/v1', publisherApiV1Router);

export default router;
